#!/bin/bash

cargo_opts="--release --example main --features=serial-compass"

cargo b $cargo_opts &&
javac -d dump test/TestDisplay.java &&
exec 3> >(java -cp dump TestDisplay) &&
cargo r $cargo_opts -q 2>&3
